language: python

python: 2.7

env:
  - TOX_ENV=

virtualenv:
  system_site_packages: true

install:
  - pip install -U 'pip<8.0' tox python-coveralls

script:
  - cd networking-odl && tox
  - coveralls
