language: python

python: 2.7

env:
  - TOX_ENV=

virtualenv:
  system_site_packages: true

install:
  pip install -U 'pip<8.0' tox python-coveralls git-review

script:
  ( cd networking-odl && tox -e pep8,cover networking_odl.common networking_odl.ml2 )

after_success:
  ( cd networking-odl && coveralls )
