#!/usr/bin/env python

import datetime
import logging
import os
from os import path
import re
import sys
import time

LOG = logging.getLogger('bash')

format_log_name = '{name}'.format
ROOT_DIR = path.dirname(path.dirname(path.abspath(__file__)))
format_log_path = path.join(
    ROOT_DIR, 'logs', '{timestamp} {description}.log').format
TIMESTAMP_FORMAT = '%y%m%d-%H%M%S'
LOG_FORMAT = '%(asctime)-15s | %(message)s'

def timestamp():
    return datetime.datetime.now().strftime(TIMESTAMP_FORMAT)

def setup_lonnging(command, level=logging.WARNING):
    logging._acquireLock()
    try:
        root = logging.root
        if len(root.handlers) == 0:
            root.setLevel(logging.DEBUG)

            formatter = logging.Formatter(LOG_FORMAT)

            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(level)
            stream_handler.setFormatter(formatter)
            root.addHandler(stream_handler)
            
            description = command.split('#', 1)[-1].strip()
            
            log_path = format_log_path(
                timestamp=timestamp(), description=description.strip())
            while path.isfile(log_path):
                time.sleep(.1)
                log_path = format_log_path(timestamp=timestamp())
    
            if path.isdir(path.dirname(log_path)):
                file_handler = logging.FileHandler(log_path, 'wt')
                file_handler.setLevel(logging.INFO)
                file_handler.setFormatter(formatter)
                root.addHandler(file_handler)
            else:
                log_path = None

            return log_path
            
    finally:
        logging._releaseLock()


def main(command):
    log_path = setup_lonnging(command)

    name = 'bash'
    logger = logging.getLogger(name)

    try:
        import sh
    except ImportError:
        logger.warning('Install: sh')
        import pip
        pip.main(['install', '--user', 'sh'])

    from sh import bash, tail
    logging.getLogger('sh').setLevel(logging.WARNING)
    
    ansi_escape = re.compile(r'\x1b[^m]*m')

    output_logger = logging.getLogger('out')
    def log_output(msg):
        output_logger.info(ansi_escape.sub('', msg[:-1]))

    error_logger = logging.getLogger('err')
    def log_error(msg):
        error_logger.info(ansi_escape.sub('', msg[:-1]))

    try:
        result = bash('-x', '-c', command, _out=log_output, _err=log_error)
    except sh.ErrorReturnCode as error:
        LOG.error(
            'Error executing command:\n'
            '    Command: %s\n'
            '    Exit code: %s\n'
            '    Log file: %s\n'
            '%s',
            command, error.exit_code, log_path, tail('-n', '25', log_path))

        return error.exit_code

    else:
        return 0


if __name__ == '__main__':
    exit(main(sys.argv[2]))
