#!/usr/bin/env python

import sys

def parse_ini_file(ini_stream):
	for line in ini_stream:
		line = line.split('#', 1)[0].strip()
		if line.startswith('['):
			section = line[1:-1]
		elif line:
			key, value = [e.strip() for e in line.split('=', 1)]
			yield section, key, value

def value_from_ini_entries(
		ini_entries, match_section, match_key, default_value=None):
	for section, key, value in ini_entries:
		if match_section == section and match_key == key:
			return value
	return default_value

def main(argv):
	filename = argv[1]
	with open(filename, 'rt') as ini_stream:
		value = value_from_ini_entries(parse_ini_file(ini_stream), *argv[2:])

	if value is None:
		return 1

	else:
		print value
		return 0

if __name__ == '__main__':
	exit(main(sys.argv))
